services:
  eventmanagementservice:
    container_name: eventmanagementservice-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env
networks:
  default:
    name: vibeverse-network
    external: true
