services:
  eventmanagementservice:
    container_name: eventmanagementservice-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env
    environment:
      - DEPLOYMENT_ENVIRONMENT=LOCAL_CONTAINER
    depends_on:
      - eventmanagement_postgres
       
  eventmanagement_postgres: 
    container_name: eventmanagement_postgres
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pubsub:
    container_name: pubsub
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    ports:
      - 8086:8085
    command: gcloud beta emulators pubsub start --project=bachelorshenanigans --host-port=0.0.0.0:8085
    environment:
      - PUBSUB_PORT=8085
      - PUBSUB_PROJECT=bachelorshenanigans   
volumes:
  postgres_data:
    driver: local
    
networks:
  default:
    name: vibeverse-network
    external: true
