name: Event Management CD flow

on:
    push:
        branches:
            - "main"
        paths:
            - src/Services/EventManagementService/EvenemtnManagementService.*/**
            - src/Services/EventManagementService/Dockerfile

jobs:
    push-container-image:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup docker
              uses: docker/setup-buildx-action@v2

            - name: Login to docker
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build image
              run: docker build -t "$DOCKERHUB_USERNAME"/vibeverse-eventmanagementservice:latest .
              working-directory: src/Services/EventManagementService
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
