name: API Gateway container image

on:
    push:
        branches:
            - "main"
        paths:
            - src/Gateway/graphify/**

jobs:
    push-container-image:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup docker
              uses: docker/setup-buildx-action@v2

            - name: Login to docker
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build image
              run: docker build --build-arg SERVICE_ACCOUNT_KEY="$SERVICE_ACCOUNT_KEY_JSON" -t "$DOCKERHUB_USERNAME"/vibeverse-gateway:latest .
              working-directory: src/Gateway/graphify
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}

            - name: Push image
              run: docker push "$DOCKERHUB_USERNAME"/vibeverse-gateway:latest
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
