name: Test EventManagementService

on:
    pull_request:
        branches:
            - "main"
        paths:
            - src/Services/EventManagementService

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "7.0.x"

            - name: Restore Dependencies
              run: dotnet restore
              working-directory: src/Services/EventManagementService

            - name: Build
              run: dotnet build -c Release --no-restore
              working-directory: src/Services/EventManagementService

            - name: Run tests
              run: dotnet test
              working-directory: src/Services/EventManagm
              env:
                  DEPLOYMENT_ENVIRONMENT: CI
                  CI: "yes"
